# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"repetition_contiguity": "Deficient_Repetition_Contiguity_Effect.ipynb",
         "recall_by_all_study_positions": "Helper_Functions.ipynb",
         "lag_crp": "Study_Phase_Retrieval_Effect.ipynb",
         "spc": "Serial_Position_Effect.ipynb",
         "recall_probability_by_lag": "Spacing_Effect.ipynb",
         "df_recall_probability_by_lag": "Spacing_Effect.ipynb",
         "repetition_connectivity_by_lag": "helpers.ipynb",
         "latent_mfc_mcf_mff": "helpers.ipynb",
         "mixed_connectivity_by_lag": "helpers.ipynb"}

modules = ["analyses.py",
           "model_evaluation.py"]

doc_url = "https://githubpsyche.github.io/repetition_cmr/"

git_url = "https://github.com/githubpsyche/repetition_cmr/tree/main/"

def custom_doc_links(name): return None
